=== api-evangelist/argo-workflows/json-schema/argo-workflows-io-k8s-api-core-v1-persistent-volume-claim-spec-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/argo-workflows/refs/heads/main/json-schema/argo-workflows-io-k8s-api-core-v1-persistent-volume-claim-spec-schema.json",
  "title": "io.k8s.api.core.v1.PersistentVolumeClaimSpec",
  "description": "PersistentVolumeClaimSpec describes the common attributes of storage devices and allows a Source for provider-specific attributes",
  "type": "object",
  "properties": {
    "accessModes": {
      "description": "accessModes contains the desired access modes the volume should have. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#access-modes-1",
      "type": "array",
      "items": {
        "type": "string"
      },
      "x-kubernetes-list-type": "atomic"
    },
    "dataSource": {
      "description": "dataSource field can be used to specify either: * An existing VolumeSnapshot object (snapshot.storage.k8s.io/VolumeSnapshot) * An existing PVC (PersistentVolumeClaim) If the provisioner or an external controller can support the specified data source, it will create a new volume based on the contents of the specified data source. When the AnyVolumeDataSource feature gate is enabled, dataSource contents will be copied to dataSourceRef, and dataSourceRef contents will be copied to dataSource when dataSourceRef.namespace is not specified. If the namespace is specified, then dataSourceRef will not be copied to dataSource.",
      "$ref": "#/definitions/io.k8s.api.core.v1.TypedLocalObjectReference"
    },
    "dataSourceRef": {
      "description": "dataSourceRef specifies the object from which to populate the volume with data, if a non-empty volume is desired. This may be any object from a non-empty API group (non core object) or a PersistentVolumeClaim object. When this field is specified, volume binding will only succeed if the type of the specified object matches some installed volume populator or dynamic provisioner. This field will replace the functionality of the dataSource field and as such if both fields are non-empty, they must have the same value. For backwards compatibility, when namespace isn't specified in dataSourceRef, both fields (dataSource and dataSourceRef) will be set to the same value automatically if one of them is empty and the other is non-empty. When namespace is specified in dataSourceRef, dataSource isn't set to the same value and must be empty. There are three important differences between dataSource and dataSourceRef: * While dataSource only allows two specific types of objects, dataSourceRef\n  allows any non-core object, as well as PersistentVolumeClaim objects.\n* While dataSource ignores disallowed values (dropping them), dataSourceRef\n  preserves all values, and generates an error if a disallowed value is\n  specified.\n* While dataSource only allows local objects, dataSourceRef allows objects\n  in any namespaces.\n(Beta) Using this field requires the AnyVolumeDataSource feature gate to be enabled. (Alpha) Using the namespace field of dataSourceRef requires the CrossNamespaceVolumeDataSource feature gate to be enabled.",
      "$ref": "#/definitions/io.k8s.api.core.v1.TypedObjectReference"
    },
    "resources": {
      "description": "resources represents the minimum resources the volume should have. Users are allowed to specify resource requirements that are lower than previous value but must still be higher than capacity recorded in the status field of the claim. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#resources",
      "$ref": "#/definitions/io.k8s.api.core.v1.VolumeResourceRequirements"
    },
    "selector": {
      "description": "selector is a label query over volumes to consider for binding.",
      "$ref": "#/definitions/io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector"
    },
    "storageClassName": {
      "description": "storageClassName is the name of the StorageClass required by the claim. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#class-1",
      "type": "string"
    },
    "volumeAttributesClassName": {
      "description": "volumeAttributesClassName may be used to set the VolumeAttributesClass used by this claim. If specified, the CSI driver will create or update the volume with the attributes defined in the corresponding VolumeAttributesClass. This has a different purpose than storageClassName, it can be changed after the claim is created. An empty string or nil value indicates that no VolumeAttributesClass will be applied to the claim. If the claim enters an Infeasible error state, this field can be reset to its previous value (including nil) to cancel the modification. If the resource referred to by volumeAttributesClass does not exist, this PersistentVolumeClaim will be set to a Pending state, as reflected by the modifyVolumeStatus field, until such as a resource exists. More info: https://kubernetes.io/docs/concepts/storage/volume-attributes-classes/",
      "type": "string"
    },
    "volumeMode": {
      "description": "volumeMode defines what type of volume is required by the claim. Value of Filesystem is implied when not included in claim spec.",
      "type": "string"
    },
    "volumeName": {
      "description": "volumeName is the binding reference to the PersistentVolume backing this claim.",
      "type": "string"
    }
  }
}

=== api-evangelist/argo-workflows/examples/argo-workflows-io-k8s-api-core-v1-persistent-volume-claim-spec-example.json
{
  "accessModes": [
    "example-accessmodes",
    "example-accessmodes"
  ],
  "dataSource": "example-datasource",
  "dataSourceRef": "example-datasourceref",
  "resources": "example-resources",
  "selector": "example-selector",
  "storageClassName": "my-workflow",
  "volumeAttributesClassName": "my-workflow",
  "volumeMode": "example-volumemode",
  "volumeName": "my-workflow"
}
