=== api-evangelist/argo-workflows/json-schema/argo-workflows-github-com-argoproj-argo-events-pkg-apis-events-v1alpha1-redis-stream-event-source-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/argo-workflows/refs/heads/main/json-schema/argo-workflows-github-com-argoproj-argo-events-pkg-apis-events-v1alpha1-redis-stream-event-source-schema.json",
  "title": "github.com.argoproj.argo_events.pkg.apis.events.v1alpha1.RedisStreamEventSource",
  "description": "github.com.argoproj.argo_events.pkg.apis.events.v1alpha1.RedisStreamEventSource schema from Argo Workflows API",
  "type": "object",
  "properties": {
    "consumerGroup": {
      "type": "string",
      "title": "ConsumerGroup refers to the Redis stream consumer group that will be\ncreated on all redis streams. Messages are read through this group. Defaults to 'argo-events-cg'\n+optional"
    },
    "db": {
      "type": "integer",
      "title": "DB to use. If not specified, default DB 0 will be used.\n+optional"
    },
    "filter": {
      "title": "Filter\n+optional",
      "$ref": "#/definitions/github.com.argoproj.argo_events.pkg.apis.events.v1alpha1.EventSourceFilter"
    },
    "hostAddress": {
      "type": "string",
      "title": "HostAddress refers to the address of the Redis host/server (master instance)"
    },
    "maxMsgCountPerRead": {
      "type": "integer",
      "title": "MaxMsgCountPerRead holds the maximum number of messages per stream that will be read in each XREADGROUP of all streams\nExample: if there are 2 streams and MaxMsgCountPerRead=10, then each XREADGROUP may read upto a total of 20 messages.\nSame as COUNT option in XREADGROUP(https://redis.io/topics/streams-intro). Defaults to 10\n+optional"
    },
    "metadata": {
      "type": "object",
      "title": "Metadata holds the user defined metadata which will passed along the event payload.\n+optional",
      "additionalProperties": {
        "type": "string"
      }
    },
    "password": {
      "title": "Password required for authentication if any.\n+optional",
      "$ref": "#/definitions/io.k8s.api.core.v1.SecretKeySelector"
    },
    "streams": {
      "description": "Streams to look for entries. XREADGROUP is used on all streams using a single consumer group.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "tls": {
      "title": "TLS configuration for the redis client.\n+optional",
      "$ref": "#/definitions/github.com.argoproj.argo_events.pkg.apis.events.v1alpha1.TLSConfig"
    },
    "username": {
      "type": "string",
      "title": "Username required for ACL style authentication if any.\n+optional"
    }
  }
}

=== api-evangelist/argo-workflows/examples/argo-workflows-github-com-argoproj-argo-events-pkg-apis-events-v1alpha1-redis-stream-event-source-example.json
{
  "consumerGroup": "example-consumergroup",
  "db": 0,
  "filter": "example-filter",
  "hostAddress": "example-hostaddress",
  "maxMsgCountPerRead": 26,
  "metadata": {},
  "password": "example-password",
  "streams": [
    "example-streams",
    "example-streams"
  ],
  "tls": "example-tls",
  "username": "my-workflow"
}
